name: Deploy to Thanker.co

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false  # This is necessary for deployments using a custom domain

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set this to your node version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Your build script

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Set this to your build directory
        cname: www.thanker.co  # Custom domain
